apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-tracker
  template:
    metadata:
      labels:
        app: task-tracker
    spec:
      containers:
        - name: task-tracker
          image: task-tracker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_TASK_SERVICE_URL
              value: 'http://task-service:4001'
            - name: REACT_APP_NOTIFICATION_SERVICE_URL
              value: 'http://notification-service:4002'
            - name: REACT_APP_ANALYTICS_SERVICE_URL
              value: 'http://analytics-service:4003'
            - name: REACT_APP_AUDIT_SERVICE_URL
              value: 'http://audit-service:4004'
---
apiVersion: v1
kind: Service
metadata:
  name: task-tracker
spec:
  selector:
    app: task-tracker
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer # Using LoadBalancer to expose the frontend
